version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: your_secret_key
      SQLALCHEMY_DATABASE_URI: mysql://flaskapp:asdadwacsa@db/db_wiad
      SQLALCHEMY_TRACK_MODIFICATIONS: 1
      ADMIN_USERNAME: kekuatanayam
      ADMIN_PASSWORD: adalahkseimbangan
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aopkdosap
      MYSQL_DATABASE: db_wiad
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: asdadwacsa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
